### ISSUE TITLE
作者在吗

### ISSUE THREAD

**Issue by 1665169869** [Coande/LandLeg_Java#1]
这是项目源码吗？我没有找到bat文件，只有dat，我希望我能继续维护此项目

**Comment by Coande** [comment]
现在应该都不能用了吧。当初说的 bat 只是 ` java -jar xxx.jar` 而已。原文地址：https://e12e.com/2016/04/16/LandLeg-Java/

**Comment by 1665169869** [comment]
当初的具体思路是怎么样的呢？我想重新制作一个

**Comment by 1665169869** [comment]
我找到了PHP的客户端，但会提示找不到SDX信息，由于没学过PHP，只能看懂比较基础的

**Comment by Coande** [comment]
不好意思我已经离开校园几年了，忘记 SDX 信息是什么了，php 那个应该很好理解吧，我也是看着那个写的。

**Comment by 1665169869** [comment]
好的，那谢谢作者告诉，我去看看

**Comment by 1665169869** [comment]
ClientID=5ebb76eb-4611-42c0-bc4a-30d5b2b6f5fd
麻烦问下，这种是什么加密方式还是？

**Comment by Coande** [comment]
> ClientID=5ebb76eb-4611-42c0-bc4a-30d5b2b6f5fd
> 麻烦问下，这种是什么加密方式还是？

这不是加密吧，这是一寸 UUID
